on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        jvm: ['8', '11']
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run all
    - id: sbt-dependency-graph-action
      uses: ./
